### ISSUE TITLE
Support for new "apple" attestation format

### ISSUE THREAD

**Issue by jtalir** [Yubico/python-fido2#100]
In recent beta releases of iOS14, Apple started to provide attestation during WebAuthn registration process. However, this attestation is of the type "apple" that is unknown to python-fido2. It would be great if library could support also this new format. This format is not registered in https://www.iana.org/assignments/webauthn/webauthn.xhtml#webauthn-attestation-statement-format-ids and I cannot find anything about it publicly.

**Comment by emlun** [comment]
Correct, the attestation statement format isn't yet standardized. The WebAuthn working group is tracking the progress here: https://github.com/w3c/webauthn/issues/1453

**Comment by jtalir** [comment]
Looks like attestation statement format has been at least described by Apple. Have you had a chance to evaluate possible implementation in this library?

**Comment by jtalir** [comment]
Will Python library be updated about at the same time as Java version as mentioned in https://github.com/Yubico/java-webauthn-server/issues/93#issuecomment-737510992?

**Comment by dainnilsson** [comment]
I won't speak for when the Java library is updated, but this is planned for inclusion in the next release (0.9) of python-fido2. While I have no exact date for that yet, it should be relatively soon (Jan-Feb).

**Comment by dainnilsson** [comment]
The feature branch with Apple attestation has now been merged to master (along with some other general attestation changes), in case you're interested in trying it out before 0.9 is released. If so, please let us know if you run into any problems!

**Comment by mkalioby** [comment]
@dainnilsson, is there any changes in the authentication to support the apple attestation, I'm able to register touch ID on both Mac and iPad but I can't authenticate with them, any advice?

**Comment by dainnilsson** [comment]
@mkalioby can you provide any details on what error you're getting? Or what's going wrong?

**Comment by mkalioby** [comment]
On Safari (on both devices), I'm not getting the Touch ID as verification option, only security key, as in version 0.8.1, even though the registration was successful. Currently, I'm testing your example server and will report back.

**Comment by mkalioby** [comment]
<img width="1188" alt="Screen Shot 2021-01-15 at 16 04 37" src="https://user-images.githubusercontent.com/10414020/104730749-a8239500-574b-11eb-9c4e-f3e1223ca344.png">
@dainnilsson, I tried your example server and as you can see that the Touch ID (isn't an option in the popup) and only the security key, can you please update the example `server.py`

**Comment by dainnilsson** [comment]
This has nothing to do with attestation (the example server doesn't use attestation at all). The example server is configured to only accept cross-platform (external) authenticators, so I assume you've made modifications to get registration working? Your issue is likely that Safari disallows the built-in authenticator for any requests that aren't triggered by the user directly (like by a button).

The example server calls the WebAuthn functions directly on load. If you wrap that code in a JavaScript function, and trigger it via a button instead, then it should work.

**Comment by mkalioby** [comment]
@dainnilsson Thank you, you got it right.
In case of Touch ID, a button shall be clicked.

Thank you.

**Comment by dainnilsson** [comment]
0.9.0 is now released, which includes support for Apple attestation.
