### ISSUE TITLE
Publish Release for 0.9.0-dev0

### ISSUE THREAD

**Issue by dillon-giacoppo** [Yubico/python-fido2#105]
The last release v0.8.1 for fido2 was on November 25 2019. There have been a number of awesome fixes since then. For example, v0.8.1 has a segfault when enumerating HID devices on MacOS Big Sur which  is all ready fixed by the new HID cleanup in a862fdaa938444faa3e3f4ef187d4a0c6a40d1b8.

Would it be possible to publish an interim release to PyPI so that the fixes can be picked up downstream. At the moment, the only way to consume it is as an egg from this repo, i.e:

```
pip install git+https://github.com/Yubico/python-fido2@507818c95ed84f543511455bc7fef646801f1cd8#egg=fido2
```

**Comment by dainnilsson** [comment]
Very glad you're finding the improvements since 0.8.1 useful! Our current plan is to release 0.9 early next year, most likely in January. Will that be "soon enough" for your use case, or is there something in the interim I can do that would be helpful?

**Comment by dainnilsson** [comment]
0.9.0 has now been released.
