### ISSUE TITLE
Unhandled exception for missing BasicConstraints

### ISSUE THREAD

**Issue by tpazderka** [Yubico/python-fido2#106]
We have recently encountered a key with missing BasicConstraint X509 extension. This causes an unhandled exception in `fido2.attestation._validate_cert_common`.

I am not sure if this extension has to be there or not, but it should be handled properly and raise `InvalidData` instead of `cryptography` exception.

**Comment by dainnilsson** [comment]
Honestly I find the spec a bit unclear on this, but my interpretation is that the extension must be there. I've pushed a change to catch this case and instead raise `InvalidData`. Please let me know if it works as intended!

**Comment by tpazderka** [comment]
Thanks! It looks like this should solve the issue we have encountered. I have no way of testing that though as we do not have the token that caused that.
