### ISSUE TITLE
Is Django left out? No enough examples.

### ISSUE THREAD

**Issue by Sirneij** [Yubico/python-fido2#118]
While checking through this project, it is quite awesome and I have been trying to integrate it with Django for an app. However, even the `flask` example was not integrated with any database. No pointers to how this can be done as well. Can't you guys provide a skeletal but working example of this project in Django with database integrated? Or is the project not being actively developed/maintained?

**Comment by mkalioby** [comment]
You can use [https://github.com/mkalioby/django-mfa2](django-mfa2) for Django integration

**Comment by Sirneij** [comment]
@mkalioby `django-mfa` doesn't meet the spec. I need a password-less system, registration should only require `some special alphanumeric characters` as username and `surname` as display name. Clicking register should bring up the platform's fingerprint scanner and touching it should send the hashed challenge as well as the username and display name to the database for storage. Then, users whose credentials have been saved can then login with only their `username` and fingerprint. No password in the entire process. I have implemented this with DUO lab's `webauthn` but it supports fewer `attestation formats` and I need to support all attestation formats including `tpm`, `android-safetynet`, and `apple`. 

This is why I need a concrete example with `python-fido2` which supports all these formats.

**Comment by mkalioby** [comment]
@Sirneij, it isn't django-mfa2 not django-mfa, and it supports all the attestation formats (keys, tpm, android safetynet and Apple) as it is based on python-fido2, the development team can help in your requirements, currently, we are using it without the use of a password and some ppl integrated it with allauth as well. so you can move the discussion to its repo.

**Comment by Sirneij** [comment]
@mkalioby If that's the case, I'll move it.

**Comment by mkalioby** [comment]
@Sirneij, I think you shall close this one.

**Comment by Sirneij** [comment]
@mkalioby Oh, let me do that. Thanks!

**Comment by Sirneij** [comment]
I have gotten it sorted out through @mkalioby assistance.
