### ISSUE TITLE
AttestationObject differences running with FIDO2Client vs WindowsClient

### ISSUE THREAD

**Issue by SAINT-SCOBBERLOTCHER** [Yubico/python-fido2#119]
**Issue**
I noticed differences with the AttestationObject when running the samples and comparing between macOS and Windows. I then also noticed that the difference presents itself when comparing running the samples on Windows in admin mode vs non-admin mode.  Is this an expected difference with FIDO2Client vs WindowsClient?  
Similarly I compared the output to attestation object shown on https://demo.yubico.com/webauthn-technical/registration and it aligns to the results of the WindowsClient results. Is the FIDO2Client returning the correct attestation object? 

**WindowsClient outputted attestation object**
WEBSAFE-ATTESTATION_OBJECT: **o2N**mbXRmcGFja2VkZ2F0dFN0bXSjY2FsZyZjc2lnWEgwRgIhAKI_CuHO5k-GhwJsFxCG61LDqAGoWsD-2MXV7RPFKnRgAiEA_JQ1xhH50L84Hn7JTJdfZr9PYS2mp4_K3KAffd1GFv1jeDVjgVkCwTCCAr0wggGloAMCAQICBB6PhzQwDQYJKoZIhvcNAQELBQAwLjEsMCoGA1UEAxMjWXViaWNvIFUyRiBSb290IENBIFNlcmlhbCA0NTcyMDA2MzEwIBcNMTQwODAxMDAwMDAwWhgPMjA1MDA5MDQwMDAwMDBaMG4xCzAJBgNVBAYTAlNFMRIwEAYDVQQKDAlZdWJpY28gQUIxIjAgBgNVBAsMGUF1dGhlbnRpY2F0b3IgQXR0ZXN0YXRpb24xJzAlBgNVBAMMHll1YmljbyBVMkYgRUUgU2VyaWFsIDUxMjcyMjc0MDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKh5-CM47RSUusBwS8x_xmPRsnFxWXYkMQHHYFEV18FSnigcHGcyLThLXNVd0-mBjV_YXCKvMm4MZPwgr-M_I2ajbDBqMCIGCSsGAQQBgsQKAgQVMS4zLjYuMS40LjEuNDE0ODIuMS43MBMGCysGAQQBguUcAgEBBAQDAgQwMCEGCysGAQQBguUcAQEEBBIEEC_AV5-BE0fqsRa7Wo25ICowDAYDVR0TAQH_BAIwADANBgkqhkiG9w0BAQsFAAOCAQEAhpP_Yt8NV3nUdI1_yNECJzGKjlgOajpXwQjpTgPDhWizZolPzlYkvko-_X80EYs9mTdD95KhmJFgyPya4LBOPfnuFePojAT8gqjcv1gY4QjcwpaFd655_2YrlHNOPexFlzBdc-blXuK-uc2WeMoJNeUz62OPjib6u4F82kQfvpgxgyrl9uKtmS-eu9tMYiOLj416tIHW0yY7zb-eSldVA3CYitWBNED6AyyttnI8rdj417qAn3W0PP-gpbmt0UIy752eFIEmOCM8TKSoc7n4rJjjK6GRZ2BuFZCfzdtKLf-9rkYgJJ-aZkasgeSDLREZ_r-qcxqILaJad4J9RtGQF2hhdXRoRGF0YViUo3mm9u6vuaVeN4wRgDTidR5oL6ufLTCrE9ISVYbOGUdFAAAAAS_AV5-BE0fqsRa7Wo25ICoAEEXNIV5ogsmtV8FyJBaEn2ClAQIDJiABIVggKm5fPVM0DrGJDlowYZXzNvbdC8rqASDXO1O0Nhp5T6MiWCAn0blM2g8rqqbpQFCCtEuvxFoq0asEXKiq8T6JkzByNw

**FIDO2Client outputted attestation object**
WEBSAFE-ATTESTATION_OBJECT: **owF**mcGFja2VkAliUo3mm9u6vuaVeN4wRgDTidR5oL6ufLTCrE9ISVYbOGUdFAAAAAi_AV5-BE0fqsRa7Wo25ICoAEKLuJTCMjd02bQd3eR1OGZOlAQIDJiABIVggINq395McTRWec_bFWrbECoicGernp2zUvzbcrzBCyfciWCCvNhnDODboxZcjKZu7_LTsbEKcsy-SRm9tYpqY1IBw0gOjY2FsZyZjc2lnWEcwRQIgBEm0iRkXHh7v-KDC6NeNXhUAX8QJl2UB_B5lwP063bwCIQDKO_jLI15CXiwOgPTft7G1hT9VnUza1qHFYvoxZWO8E2N4NWOBWQLBMIICvTCCAaWgAwIBAgIEHo-HNDANBgkqhkiG9w0BAQsFADAuMSwwKgYDVQQDEyNZdWJpY28gVTJGIFJvb3QgQ0EgU2VyaWFsIDQ1NzIwMDYzMTAgFw0xNDA4MDEwMDAwMDBaGA8yMDUwMDkwNDAwMDAwMFowbjELMAkGA1UEBhMCU0UxEjAQBgNVBAoMCVl1YmljbyBBQjEiMCAGA1UECwwZQXV0aGVudGljYXRvciBBdHRlc3RhdGlvbjEnMCUGA1UEAwweWXViaWNvIFUyRiBFRSBTZXJpYWwgNTEyNzIyNzQwMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEqHn4IzjtFJS6wHBLzH_GY9GycXFZdiQxAcdgURXXwVKeKBwcZzItOEtc1V3T6YGNX9hcIq8ybgxk_CCv4z8jZqNsMGowIgYJKwYBBAGCxAoCBBUxLjMuNi4xLjQuMS40MTQ4Mi4xLjcwEwYLKwYBBAGC5RwCAQEEBAMCBDAwIQYLKwYBBAGC5RwBAQQEEgQQL8BXn4ETR-qxFrtajbkgKjAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4IBAQCGk_9i3w1XedR0jX_I0QInMYqOWA5qOlfBCOlOA8OFaLNmiU_OViS-Sj79fzQRiz2ZN0P3kqGYkWDI_JrgsE49-e4V4-iMBPyCqNy_WBjhCNzCloV3rnn_ZiuUc0497EWXMF1z5uVe4r65zZZ4ygk15TPrY4-OJvq7gXzaRB--mDGDKuX24q2ZL56720xiI4uPjXq0gdbTJjvNv55KV1UDcJiK1YE0QPoDLK22cjyt2PjXuoCfdbQ8_6Clua3RQjLvnZ4UgSY4IzxMpKhzufismOMroZFnYG4VkJ_N20ot_72uRiAkn5pmRqyB5IMtERn-v6pzGogtolp3gn1G0ZAX

**demo.yubico.com outputted attestation object**
**o2N**mbXRmcGFja2VkZ2F0dFN0bXSjY2FsZyZjc2lnWEgwRgIhANCQUe0I6UpBf9vw+yXu6FVNGjLWT6JVTYl81mx+B+GrAiEA6q4WTBx4eVWjKGFotxEL/6Bf2wE8irTo/YxDfE/+F7BjeDVjgVkCwjCCAr4wggGmoAMCAQICBF3QTuEwDQYJKoZIhvcNAQELBQAwLjEsMCoGA1UEAxMjWXViaWNvIFUyRiBSb290IENBIFNlcmlhbCA0NTcyMDA2MzEwIBcNMTQwODAxMDAwMDAwWhgPMjA1MDA5MDQwMDAwMDBaMG8xCzAJBgNVBAYTAlNFMRIwEAYDVQQKDAlZdWJpY28gQUIxIjAgBgNVBAsMGUF1dGhlbnRpY2F0b3IgQXR0ZXN0YXRpb24xKDAmBgNVBAMMH1l1YmljbyBVMkYgRUUgU2VyaWFsIDE1NzM5MzI3NjkwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQjaeALPlEZ1qm00Ye+tEGAzaxx6lKYgePnfRz1gaE7ZzErqTKGNZ3DSA2BE9ZeFBTs5tEOuy0eyN2aPwL9XIDUo2wwajAiBgkrBgEEAYLECgIEFTEuMy42LjEuNC4xLjQxNDgyLjEuNzATBgsrBgEEAYLlHAIBAQQEAwIEMDAhBgsrBgEEAYLlHAEBBAQSBBAvwFefgRNH6rEWu1qNuSAqMAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggEBAIfKHSVOKPRSFGEpt4dVIa0xn57pHMxSXd6IxCZ8c2QZwwcnu1X81RSdOVUM7vOfRyN5kcSuRR+By6Oi51ayqyoe3DxIRAq0IBIG7YyMA/gAF0JAAGU9Xsp4Oe9qPNqP+lGvXtPzfgZLV1d08MzxoDEGlhoKpeNYMokXPvGAQW1hfqM6M70U9ofqnsaXe2MD1ZOhUYi4TcoqoZfaqZ62h7a3EMhJfvuTzJwlEsoDcik80vQx+3fBvqkxWVdt23XnAMo0thHH87RS0rNALuvoyy77fUdKYxltvJDmxPBfQQZCbSymbT2sN1vy8mVzsbNzyvohDTOSt1LW2yjz4tmvwGFoYXV0aERhdGFYxMRs74KtG1Rkd1kdAIsIdZ7D5tLstPOUdL/qaWmSXQO3RQAAAAMvwFefgRNH6rEWu1qNuSAqAEAQtsAXx76PX5ADrL4sku1RieSK7XjwefVyJNREXt0fGyLKIpZrP0xieiD0MQcn0KHitd31qwXjS7kd/CskKMWypQECAyYgASFYIBCYXlhBwD4ozqEgYduuUDxbzOo1YprccNrxzKrFQCOrIlggLGMG8DuWV5c8eSCw+bm90+O0NCYVI2jtF3QGRxTWqpY=

**Steps to Repro**
Using examples/resident_key.py

1. Modify example to add a line after make_credential to `print("\nWEBSAFE-ATTESTATION_OBJECT:", websafe_encode(result.attestation_object))`
2. Open command prompt in admin mode.
2. `python resident_key.py`
3. View attestation output
4. Open command prompt without admin
5. `python resident_key.py`
6. View attestation outputs and compare the results.

**Comment by dainnilsson** [comment]
Looks like an inconsistency in the format, where the Windows API returns the "webauthn-style" format of using strings as keys, but the native one uses the "CTAP-style" format using integers. This should be made consistent (probably to use "webauthn-style" in both cases). Unfortunately this will be a slight break in backwards compatibility.

**Comment by dainnilsson** [comment]
python-fido2 1.0.0rc1 has now been released (with the final coming in about a month) and in it this has been resolved.
