### ISSUE TITLE
ClientData from dict?

### ISSUE THREAD

**Issue by 0x0ece** [Yubico/python-fido2#12]
How about creating ClientData from a dict, and having a `from_json` to decode from a str?
https://github.com/Yubico/python-fido2/blob/492eac92201cef9929f47f3e9eeb95aef056baf7/fido2/client.py#L45

(In my case, for example, the api layer already takes care about json decoding)

**Comment by dainnilsson** [comment]
The reason that ClientData requires bytes (or base64 encoded data) is that the exact binary serialization used is important to maintain the sha256 digest. De-serializing this data, and then re-serializing it to get the raw bytes has a large chance of introducing changes in the data (for example the order of the fields, any whitespace changes, and so on), which would cause the digest to no longer match, and the signature validation to fail. For this reason, we don't allow it.

**Comment by ziima** [comment]
Is that also true for `AuthenticatorData`, `AttestedCredentialData` and other structures?

**Comment by dainnilsson** [comment]
Yes, the binary representations of these are signed during attestation.

**Comment by ziima** [comment]
> De-serializing this data, and then re-serializing it to get the raw bytes has a large chance of introducing changes in the data (for example the order of the fields, any whitespace changes, and so on), which would cause the digest to no longer match, and the signature validation to fail. For this reason, we don't allow it.

I don't think, you can prevent that. As the `AuthenticatorData` and other objects have serialization method `create` and provide deserialized data, such as `rp_id_hash`, `flags`, etc. Anybody can extract they individually, serialize and the deserialize and create the object again.

**Comment by dainnilsson** [comment]
Yeah, maybe the wrong choice of wording on my part. What I meant was that where possible, we should make it hard for a consumer of the library to accidentally mess things up. The example of re-creating the ClientData from a dict which was previously deserialized from JSON is a prime example of this, as it may result in a different byte representation for the ClientData, which woulc cause the server to reject the operation. The only clue as to what was happening would be an "Invalid signature" error, so debugging the issue could be difficult.
