### ISSUE TITLE
Allow HTTP on localhost

### ISSUE THREAD

**Issue by GramThanos** [Yubico/python-fido2#122]
Although HTTPS is mandatory, HTTP is allowed on localhost.
Here is the code in question:

https://github.com/Yubico/python-fido2/blob/142587b3e698ca0e253c78d75758fda635cac51a/fido2/rpid.py#L54-L76

I propose to change: 
https://github.com/Yubico/python-fido2/blob/142587b3e698ca0e253c78d75758fda635cac51a/fido2/rpid.py#L69-L70

to something like:
```python
if url.scheme != "https" and not (url.scheme == "http" and url.hostname == "localhost"):
    return False
```

Any feedback on that?
Any pros or cons that you see?

**Comment by dainnilsson** [comment]
> Although HTTPS is mandatory, HTTP is allowed on localhost.

I can't find any mention in the spec that says that HTTP is allowed on localhost. If I'm missing it, can you point it out?
What I do see here https://www.w3.org/TR/webauthn-2/#rp-id is that "The origin's scheme must be https.".

**Comment by GramThanos** [comment]
I see your point. Though this come a bit in conflict, with the [API exposure part](https://www.w3.org/TR/webauthn-2/#sctn-api):

> Since this is an integral part of the WebAuthn security model, user agents only expose this API to callers in secure contexts.

As browsers are allowed to consider [localhost as a secure context](https://w3c.github.io/webappsec-secure-contexts/#localhost) even over HTTP.

For me, this was a problem only during development, where I had to manually disable the origin verification, example:

```python
server = fido2.server.Fido2Server({'id': hostname, 'name': 'Relying Party Name'}, verify_origin=(lambda o: True))
```

**Comment by dainnilsson** [comment]
Since this can be worked around by setting a custom `verify_origin` function, we will close this issue and suggest that as the solution if non-https localhost is required.

**Comment by humphrey** [comment]
> Since this can be worked around by setting a custom verify_origin function, we will close this issue and suggest that as the solution if non-https localhost is required.

Thanks for this info.  For anybody else who's stumbled across this issue like I did, the [django-mfa3](https://github.com/xi/django-mfa3/) package has [now been updated](https://github.com/xi/django-mfa3/pull/17) to use a custom `verify_origin` function as suggested above.
