### ISSUE TITLE
local debugging of the server example

### ISSUE THREAD

**Issue by nanonybit** [Yubico/python-fido2#131]
Hi there,

I was trying to run the application locally.
every time I click on the register button I am receiving an error saying: "SecurityError: This is an invalid domain."
could you please assist

Thanks

**Comment by mkalioby** [comment]
What is the address you are using on your browser's address bar?

**Comment by nanonybit** [comment]
I tried using https://0.0.0.0:5000, https://127.0.0.1:5000 and https://localhost:5000

**Comment by nanonybit** [comment]
actually
