### ISSUE TITLE
Example Server - NotAllowedError on macOS and iOS

### ISSUE THREAD

**Issue by volzon** [Yubico/python-fido2#134]
When using the example server I get the error: "NotAllowedError: This request has been cancelled by the user." on macOS and iOS units. There is some info here: https://support.yubico.com/hc/en-us/articles/360022004600-No-reaction-when-using-WebAuthn-on-macOS-iOS-and-iPadOS

I noticed that this is not a problem at demo.yubico.com

Is it possible to add a fix for this in the example server?

**Comment by dainnilsson** [comment]
Hi! This has now been fixed on the master branch.
