### ISSUE TITLE
Connected security key supports BioEnrollment check is always FALSE

### ISSUE THREAD

**Issue by PranithaReddyAedla** [Yubico/python-fido2#151]
While checking if connected security key supports biometrics is always being detected as " does not support" for either of the keys.

```
for device in CtapHidDevice.list_devices():
    try:
        ctap = Ctap2(device)
        if "bioEnroll" in ctap.info.options:
            break
    except Exception:  # nosec
        continue
else:
    print("No Authenticator supporting bioEnroll found")
    sys.exit(1)
```

**Comment by dainnilsson** [comment]
What kind of keys are you trying this with?

**Comment by PranithaReddyAedla** [comment]
@dainnilsson "FEITIAN BioPass FIDO2 K26" and "FEITIAN AllinPass FIDO2 K33"  Security Keys

**Comment by dainnilsson** [comment]
Using the included `examples/get_info.py` script, can you provide the Device Info for each of these devices?

**Comment by PranithaReddyAedla** [comment]
```
CONNECT: CtapHidDevice(b'\\\\?\\hid#vid_096e&pid_085d&mi_00#7&287a6ee3&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}')
CTAPHID protocol version: 2
DEVICE INFO: {<VERSIONS: 0x01>: ['U2F_V2', 'FIDO_2_0', 'FIDO_2_1_PRE'], <EXTENSIONS: 0x02>: ['credProtect', 'hmac-secret'], <AAGUID: 0x03>: b'w\x01\x0b\xd7!*O\xc9\xb26\xd2\xca^\x9d@\x84', <OPTIONS: 0x04>: {'rk': True, 'up': True, 'uv': True, 'plat': False, 'clientPin': True, 'credentialMgmtPreview': True, 'userVerificationMgmtPreview': True}, <MAX_MSG_SIZE: 0x05>: 2048, <PIN_UV_PROTOCOLS: 0x06>: [1], <MAX_CREDS_IN_LIST: 0x07>: 10, <MAX_CRED_ID_LENGTH: 0x08>: 96, <TRANSPORTS: 0x09>: ['usb'], <ALGORITHMS: 0x0A>: [{'alg': -7, 'type': 'public-key'}]}
WINK sent!

CONNECT: CtapHidDevice(b'\\\\?\\hid#vid_096e&pid_0866&mi_00#8&3b1c21f9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}')
CTAPHID protocol version: 2
DEVICE INFO: {<VERSIONS: 0x01>: ['FIDO_2_0', 'FIDO_2_1_PRE'], <EXTENSIONS: 0x02>: ['credProtect', 'hmac-secret'], <AAGUID: 0x03>: b'\x12\xde\xd7EK\xedG\xd4\xab\xaa\xe7\x13\xf5\x1dc\x93', <OPTIONS: 0x04>: {'rk': True, 'up': True, 'uv': True, 'plat': False, 'clientPin': True, 'credentialMgmtPreview': True, 'userVerificationMgmtPreview': True}, <MAX_MSG_SIZE: 0x05>: 2048, <PIN_UV_PROTOCOLS: 0x06>: [1], <MAX_CREDS_IN_LIST: 0x07>: 10, <MAX_CRED_ID_LENGTH: 0x08>: 96, <TRANSPORTS: 0x09>: ['usb'], <ALGORITHMS: 0x0A>: [{'alg': -7, 'type': 'public-key'}]}
WINK sent!
```

Note: `product_name` and `serial_number` attributes are absent, so commented them.

**Comment by dainnilsson** [comment]
This should now be fixed in [cd9e6cb](https://github.com/Yubico/python-fido2/commit/cd9e6cbd595118e93d38a9d2535e36576df9abb9). Can you try using the latest version from `main` and seeing if that works for you?

**Comment by PranithaReddyAedla** [comment]
@dainnilsson It worked. Thanks for quick response. When can we expect this in next release? Any ETA please!

And Do we have any method to check if security key(which is supporting bioenrollment) has fingerprint setup already or not?

**Comment by dainnilsson** [comment]
The next release will likely be in October. However, you don't really need to wait for a new release for this. The functionality of BioEnrollment should work fine, it's only the `is_supported()` check that doesn't handle this. You can perform the check manually for now as a workaround: https://github.com/Yubico/python-fido2/blob/main/fido2/ctap2/bio.py#L65

**Comment by PranithaReddyAedla** [comment]
@dainnilsson Thank you. Yeah, We will do that to check manually. 

Do we have any method/way to check if security key(which is is_supported() true) has fingerprint setup already or not?

**Comment by dainnilsson** [comment]
Yes, the ctap2.info.options dict can tell you that.
Instead of just checking for the existance of `bioEnroll` or `userVerificationMgmtPreview` check what value it has. If at least one fingerprint has been set up it will be `true`, `false` otherwise.

**Comment by PranithaReddyAedla** [comment]
@dainnilsson When 2 or more devices are connected, Is there a way to pass device ID - like "bd6GEbWtEakT_tSDjpqN8SIqxMiZ9PB554BeOXHapfv0KRb1VA0U15X4XIViY5kGD6iShjUE4fHzV1XKcB78D2w7Dl3-MiESdk8e3agr4pkLO72UbYe0D2JDKcAHEJGS" to identify if it supports biometrics?

**Comment by dainnilsson** [comment]
I don't know what you mean by "device ID". If you're talking about the Credential ID then no, there isn't anything in that which will tell you if its device supports biometrics or not.

**Comment by PranithaReddyAedla** [comment]
Yeah, I am talking about "Credential ID". Thank you for the response.
