### ISSUE TITLE
U2F validation issue

### ISSUE THREAD

**Issue by YashwanthLokam** [Yubico/python-fido2#154]
Hi, I am unable to find a class for U2F authn and enrollment in the latest fido2 1.0 lib. In the previous versions of lib, we have U2FClient class. Can anyone help me on how to authn and enroll a U2F device using the latest fido2 1.0 lib?

**Comment by dainnilsson** [comment]
U2F has been deprecated and is unsupported in favor of FIDO2/WebAuthn. Is there a reason you need to support U2F?

**Comment by YashwanthLokam** [comment]
We are supporting U2F using the previous lib. Do you plan to deprecate U2F support in the previous lib versions as well?

**Comment by dainnilsson** [comment]
When you say "the previous lib", are you referring to past versions of python-fido2, or something else? Any previous versions exists as-is, and won't be changed.
