### ISSUE TITLE
Error in verify_attestation.py example

### ISSUE THREAD

**Issue by BananasRule** [Yubico/python-fido2#155]
## Issue
verify_attestation.py throws error 

> Traceback (most recent call last):
  File "C:/fake_path/verify_attestation.py", line 142, in <module>
    if use_prompt:
NameError: name 'use_prompt' is not defined

## Environment
Python version: 3.10.2
OS: Windows 11

## Quick fix
Add 
> use_prompt = None

to main body of code immediately after imports

## Guess at issue

use_prompt is defined within a function and not the main block. When called on line 142 it is not defined as it is a function only variable. Defining it in main removes this problem.

**Comment by BananasRule** [comment]
use_prompt may need to be set to true or false in main to achieve desired behavior.

**Comment by dainnilsson** [comment]
Thanks! The `use_prompt` variable should no longer be used and I have now removed it from that example.
