### ISSUE TITLE
How can I get the attestation type from Fido2Server?

### ISSUE THREAD

**Issue by drewcapener** [Yubico/python-fido2#158]
I am working on an application that requires me to retrieve the attestation type as described [here](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#attestation-ca). I would expect this to be returned from the call to `register_complete`. But, I haven't been able to find the info there. It looks like this value maybe has to be resolved as a part of verification in which case maybe I need to pass in a function for `verify_attestion` in the Fido2Server constructor? If so, what would I pass in there? Just a bit turned around here. Any help would be much appreciated.

**Comment by dainnilsson** [comment]
The attestation type isn't really exposed by Fido2Server. You could do something like what you're describing with `verify_attestation` to capture the type as it's being verified. The base `AttestationVerifier` class will extract the type during verification, and it will be passed to the `ca_lookup` method. If you're subclassing AttestationVerifier you could here perform some logic against the type, or store it somewhere to access later.

Alternatively you run `register_complete` as usual, and once it's done, use the same approach as the AttestationVerifier class uses to get the type: https://github.com/Yubico/python-fido2/blob/main/fido2/attestation/base.py#L211

**Comment by drewcapener** [comment]
Thanks @dainnilsson. I'll close this issue.
