### ISSUE TITLE
How can I base64url encode auth_data.credential_data.public_key?

### ISSUE THREAD

**Issue by drewcapener** [Yubico/python-fido2#159]
I am working on an application that requires me to store the public key base64url encoded. I expected that I could use `websafe_encode` to do it but haven't had any luck there or with standard functions. Thanks in advance for any help!

**Comment by dainnilsson** [comment]
The public key is a COSE public key, which is a key-value map. You have to define a way to encode it to binary before you can encode it to base64. Depending on what the application expects there, this could be done in several ways, although the most common would be to encode it using CBOR. In that case, you would do the following:

```py
from fido2 import cbor
from fido2.utils import websafe_encode

encoded = websafe_encode(cbor.encode(auth_data.credential_data.public_key))
```

**Comment by drewcapener** [comment]
Excellent, thank you.
