### ISSUE TITLE
Example not working. no popup coming up to say that the registration is successful.

### ISSUE THREAD

**Issue by hhammoud01** [Yubico/python-fido2#160]
I am trying to run the example to get started with this library, however no popup comes up to confirm registration complete. And no logs on the terminal running the server.
How do I run the example ?

**Comment by dainnilsson** [comment]
Are you getting the page to load at all? Can you enable the browsers developer console and try registering, and seeing if there is an error there?

**Comment by hhammoud01** [comment]
> 

Thank you for replying. This is my environment:
MACOS 12.2.1
Python 3.9.9

Installed all the requirements as mentioned in the README, as well as running the example server using poetry.
I had to copy the files from "fido2/" folder to my fido2 folder installed by pip to solve some dependency issues.
Page is loading, registration page is loading and it tells me to "touch my hardware key". After which nothing happens.
In the terminal that's running the server, there is no error and no single line of log.

I have read somewhere that WebAuthn requires to be run in an actual domain name. This means that simple "127.0.0.1" will not work. Could this be the problem ?

Thank you.

**Comment by hhammoud01** [comment]
Thank you. it works with localhost.
