### ISSUE TITLE
To determine if security key is set with pin or not

### ISSUE THREAD

**Issue by PranithaReddyAedla** [Yubico/python-fido2#167]
With the latest versions, Is there a way to determine if a security key is configured with PIN or not?

**Comment by dainnilsson** [comment]
On client side, you can just check the `clientPin` option in the `Ctap2.info` object. If present, PIN is supported. If `true`, a PIN is set.

On the server side, you can only see if UV (User Verification) was performed for an action or not, where UV *might* have been provided by a PIN, but could also be provided by another method, such as a fingerprint scan.
