### ISSUE TITLE
How to  save credentials on server

### ISSUE THREAD

**Issue by the2nd** [Yubico/python-fido2#168]
Hi,

currently i am trying to migrate my authentication server from u2f to fido.

I found examples/credential.py which works on my test setup. With u2f there was the key handle to be saved on server side. How does this work with fido? What part must be saved on server side after token registration?

Thanks a lot for any help.

**Comment by the2nd** [comment]
> Hi,
> 
> currently i am trying to migrate my authentication server from u2f to fido.
> 
> I found examples/credential.py which works on my test setup. With u2f there was the key handle to be saved on server side. How does this work with fido? What part must be saved on server side after token registration?
> 
> Thanks a lot for any help.

Okay after some investigation was able to export credential data as hex:
hex_dump = auth_data.credential_data.hex()

and load it with:
credential_data = AttestedCredentialData(bytes.fromhex(hex_dump))

**Comment by dainnilsson** [comment]
Many of the data types used in WebAuthn are binary types (`bytes` in Python) and can be stored either as blobs in a database, or serialized to string in some way, like hex for instance as you are doing. Either of these approaches are fine, and depend on what is convenient for your purposes. I'm glad you found a solution that works!
