### ISSUE TITLE
Does this work with Touch ID on a Mac

### ISSUE THREAD

**Issue by nsandhu-godaddy** [Yubico/python-fido2#170]
I am listing devices like this:
```
def main():
  print(list(list_devices()))
  return
```

It is only printing one device, which is my yubikey. Does this library work with Macbook Touch ID?

**Comment by dainnilsson** [comment]
The client portion of this library supports USB (HID) and NFC (PC/SC) based FIDO authenticators. Credentials tied to the platform itself are only supported if the platform authenticator conforms to either of these interfaces.

The server portion will work fine with any type of WebAuthn-compatible credential, including TouchID.

**Comment by nsandhu-godaddy** [comment]
ok thank you!
