### ISSUE TITLE
Login with fingerprint

### ISSUE THREAD

**Issue by calambrenet** [Yubico/python-fido2#186]
Hello, I am creating an authentication system for a website without username and password. That is, by scanning the fingerprint the user will be able to log in directly. Then I need the key (or whatever it is called) of each user and look it up in the database. If the user previously registered his fingerprint he will be able to log in without username and password.

I'm trying to do it using this library and I'm afraid it's not possible. Is it possible? Is there any limitation to do what I need to do?

Thank you.

**Comment by mkalioby** [comment]
Which framework are you using?

**Comment by calambrenet** [comment]
Django

**Comment by mkalioby** [comment]
You can use [django-passkeys](https://github.com/mkalioby/django-passkeys) or [django-mfa2](https://github.com/mkalioby/django-mfa2) which uses this library to achieve your requirements

**Comment by calambrenet** [comment]
jango-passkeys I don't know, I'll try it. django-mfa2 I've played with it a bit and the problem I see is that you need to indicate which user is logging in using the username. Then you enter the fingerprint to validate. So it's not quite what I need. 

Isn't there any method in the library that, when touching the reader, returns the key to look it up in the database?
Thank you very much.

**Comment by mkalioby** [comment]
Your scenario is passkeys that the key identifies the user.

**Comment by calambrenet** [comment]
Thank you
