### ISSUE TITLE
fido2.webauthn.AttestedCredentialData.__init__ is missing type annotation

### ISSUE THREAD

**Issue by cuu508** [Yubico/python-fido2#205]
The fido2 library has the py.typed marker (awesome!), but the `fido2.webauthn.AttestedCredentialData.__init__` has an argument `_` with no type annotation, and has no return type. This leads to a mypy warning in calling code (when run with `--strict`):

```
path/to/file.py:22: error: Call to untyped function "AttestedCredentialData" in typed context  [no-untyped-call]
```

I'm not sure what the correct annotation would be. Anything that can be passed into `bytes()`? Or perhaps simply `Any`?

**Comment by dainnilsson** [comment]
I'm not sure I see much benefit in getting it to pass with `--strict`, compared to the effort required. I get close to 500 errors when I run mypy with `--strict` currently.

To answer your question though, yes, the argument passed to __init__ there is anything that can be passed into `bytes()`.

**Comment by cuu508** [comment]
> I'm not sure I see much benefit in getting it to pass with --strict, compared to the effort required. I get close to 500 errors when I run mypy with --strict currently.

No argument. Getting the 500 errors fixed may require not just adding type hints but sometimes also making subtle changes to the implementation. Which takes effort, especially for security-sensitive code.

Perhaps the type hints can be added in a few select places, to allow *client code* to pass mypy checks with `--strict`? In my project's case, the `AttestedCredentialData` constructor is the only place that mypy complains about. If I add a type hint in that single place, mypy is happy.

The easiest fix would be to annotate it as:

```python
    def __init__(self, _: Any):
```

A more precise annotation would be:

```python
    def __init__(self, _: Union[int, bytes]):
```

Mypy accepts `bytearray` and `memoryview` objects for arguments annotated as `bytes`, so they don't need to be listed separately. As a quick experiment, mypy is fine with this:

```python
from typing import Union


class Foo(bytes):
    def __init__(self, _: Union[int, bytes]):
        super().__init__()


Foo(10)
Foo(b"foo")
Foo(bytearray(b"foo"))
Foo(memoryview(b"foo"))
```

**Comment by dainnilsson** [comment]
Fair enough! Actually, I had forgotten about the `bytes(int)` constructor. That would never result in a valid `AttestedCredentialData`, so just using `bytes` as a valid type should be sufficient, given the allowance for bytearray and memoryview.
