### ISSUE TITLE
No Serial number in dev property 

### ISSUE THREAD

**Issue by YashwanthLokam** [Yubico/python-fido2#208]
Hi @dainnilsson,
   I am looking for serial number of the Yubico BIO FIDO series key using the latest fido2 package. 
![image (6)](https://github.com/Yubico/python-fido2/assets/73385194/2b1389a8-ba97-416e-b206-11c9ae902786)
It is showing None for Serial number attribute despite the serial number on the back of the key. Is there any other way to find the Serial number?

**Comment by dainnilsson** [comment]
Not specifically with this library, but it can be done using https://github.com/Yubico/yubikey-manager, with the relevant bits being reading the DeviceInfo data: https://github.com/Yubico/yubikey-manager/blob/main/yubikit/management.py#L438 and then parsing it: https://github.com/Yubico/yubikey-manager/blob/main/yubikit/management.py#L234
