### ISSUE TITLE
occasional `Unexpected run loop exit code: 3` printed to stderr when prompting for UP

### ISSUE THREAD

**Issue by glyph** [Yubico/python-fido2#210]
When this happens, I usually have to touch the authenticator a few times; the library appears to block somewhere. I haven't investigated particularly thoroughly but I mostly use macOS and I don't think I've seen this on Linux.

**Comment by dainnilsson** [comment]
Would you be able to test the `dain/macos-runloop-error` branch and see if that fixes the problem for you?

**Comment by glyph** [comment]
Sorry I missed that ping! I will try out an install from `main` to check it out.

**Comment by glyph** [comment]
@dainnilsson  Looks like that has fixed it. Thank you so much for addressing this annoying issue! Do you happen to know when a new PyPI release will be available?

**Comment by dainnilsson** [comment]
Great! Hoping to have a new release out by the end of the week!

**Comment by glyph** [comment]
Fantastic. Fixing this little annoyance really improves the apparent fit & finish of the whole library :)
