### ISSUE TITLE
Discoverable credential Authentication

### ISSUE THREAD

**Issue by techbird** [Yubico/python-fido2#238]
Firstly, thank you for developing such an exemplary piece of software.  I am learning , slowly feeling my way, but may I ask... 

examples/resident_key.py runs perfectly but if I wanted to subsequently write some python to just authenticate the preexisting credential (as created by resident_key.py) without a registration step, how is this possible as the needed AttestedCredentialData is not available and only available via auth_data as returned by register_complete  ?

```
# Complete registration
**auth_data** = server.register_complete(
    state, result.client_data, result.attestation_object
)
credentials = [**auth_data**.credential_data]
```

Is there  a python example which just authenticates a discoverable/resident credential without a prior register in the same run?

**Comment by mkalioby** [comment]
You need to convert the `auth_data.credential_data` into a serializable and store it in a file or database column as you like.
One of the ways to serialize is to use `websafe_encode` as follows

```python
from fido2.utils import  websafe_encode
encoded = websafe_encode(auth_data.credential_data)
```

to be able to decode it again you do the following

```python
from fido2.utils import  websafe_decode
from fido2.webauthn import AttestedCredentialData

credentials = [AttestedCredentialData(encoded)]
                       
```

**Comment by techbird** [comment]
Dear mkalioby, thank you for the nudge in the right direction.

So I understand the RP will be responsible for stashing the cred data for the discoverable credential as returned during registration; this includes the cred's public key. Whereas the private key and other resident data is held on the security key itself.

I'll do a bit of reading to ensure I understand the various responsibilities.

**Comment by mkalioby** [comment]
Yes correct.

You need to store the public key to be able to decrypt the received encrypted challenge and compare with the sent challenge
