### ISSUE TITLE
USER_VERIFICATION PREFERRED not working in server.py

### ISSUE THREAD

**Issue by meroujanantonyan** [Yubico/python-fido2#24]
Hello,

I am trying to run server.py:
server = Fido2Server(rp, user_verification=USER_VERIFICATION.PREFERED) works fine. 
server = Fido2Server(rp, user_verification=USER_VERIFICATION.REQUIRED) no prompt from browser or os.. 

Is the field decoded in cbor.js or its not implemented ?

Thank you

**Comment by syntaxcase** [comment]
Hi,
this could be the browser not supporting user verification, and consequently doing nothing when userVerification is required. I did a quick test, the current stable Chrome will show the interaction dialog, but won't allow interacting with any connected YubiKey (they don't start blinking). The only browser supporting user verification at the moment is Microsoft Edge.

**Comment by dainnilsson** [comment]
Closing this as I suspect it's due to browser (in)compatibility, rather than an issue with the library.
