### ISSUE TITLE
Potential removal of webauthn_json_mapping?

### ISSUE THREAD

**Issue by koalo** [Yubico/python-fido2#241]
Hi,
I just noticed that 023e880 has introduced the statement "# TODO 2.0: Remove this feature" for webauthn_json_mapping.
What is the reason for that @dainnilsson ?
Especially since browsers have just introduced parseRequestOptionsFromJSON(): https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/parseRequestOptionsFromJSON_static

Thanks,
Florian

**Comment by koalo** [comment]
Sorry, just stumbled upon https://github.com/Yubico/python-fido2/issues/169#issue-1519010262
So apparently I just misread your comment and thought you want to remove JSON support instead of making it default. Sorry!

**Comment by tomandersen** [comment]
With the release of 2.0 This feature is now crashing allauth: https://codeberg.org/allauth/django-allauth/issues/4398
https://codeberg.org/allauth/django-allauth/issues/4398

(which looks like allauth just fixed )
