### ISSUE TITLE
server example is broken against 0.4.0

### ISSUE THREAD

**Issue by origliante** [Yubico/python-fido2#27]
Recent changes in example endpoint register_begin require two values returning from server.register_begin
but just one is coming in 0.4.0, leading to:
  File "/server/server.py", line 73, in register_begin
    }, credentials)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by dainnilsson** [comment]
If you're running the example from master, then you have to use the library for master as well.

**Comment by origliante** [comment]
That makes sense. Thanks :-)
