### ISSUE TITLE
pip install broken in 2.7 env

### ISSUE THREAD

**Issue by origliante** [Yubico/python-fido2#28]
If you comment out this from setup.py:

    extras_require={
        ':python_version < "3.4"': ['enum34']
    },

it works again. Error is:

  Downloading https://files.pythonhosted.org/packages/58/0d/655ef526ab14b8eecc70f773294f15b23402d5184da290c4f23d5d893048/fido2-0.4.0.tar.gz (141kB)
    100% |████████████████████████████████| 143kB 6.6MB/s
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in fido2 setup command: Invalid environment marker: python_version < "3.4"

**Comment by dainnilsson** [comment]
Your version of setuptools is likely outdated. Try updating it and then installing fido2 again.
