### ISSUE TITLE
Confusion about CTAPHID response cmd field for CBOR messages

### ISSUE THREAD

**Issue by conorpp** [Yubico/python-fido2#3]
The following code from [fido2/hid.py](https://github.com/Yubico/python-fido2/blob/master/fido2/hid.py#L83) assumes that successful CTAPHID responses will have the same command field as the initial request.

```python
    def call(self, cmd, data=b'', event=None, on_keepalive=None):
        event = event or Event()
        self._dev.InternalSend(TYPE_INIT | cmd, bytearray(data))
        last_ka = None
        while not event.is_set():
            status, resp = self._dev.InternalRecv()
            status ^= TYPE_INIT
            if status == cmd:
                return bytes(resp)
            elif status == CTAPHID.ERROR:
                raise CtapError(resp[0])
            elif status == CTAPHID.KEEPALIVE:
                ka_status = resp[0]
                if on_keepalive and last_ka != ka_status:
                    try:
                        ka_status = STATUS(ka_status)
                    except ValueError:
                        pass  # Unknown status value
                    last_ka = ka_status
                    on_keepalive(ka_status)
                continue
            else:
                raise CtapError(CtapError.ERR.INVALID_COMMAND)

        self.call(CTAPHID.CANCEL, b'', _SingleEvent())
        raise CtapError(CtapError.ERR.KEEPALIVE_CANCEL)
```

[In the CTAP spec, for HID CBOR requests](https://fidoalliance.org/specs/fido-v2.0-ps-20170927/fido-client-to-authenticator-protocol-v2.0-ps-20170927.html#ctaphid_cbor-0x10), it says the response should use CTAPHID_MSG in the command field (rather than CTAPHID_CBOR).  Is this a mistake in the spec?

**Comment by dainnilsson** [comment]
It looks to me like a copy-paste error in the spec. It doesn't really make sense for that one command to expect a different response than all the others. I'm working on the assumption that the code is correct and the spec is wrong in this instance.
