### ISSUE TITLE
Serialize auth_data.credential_data

### ISSUE THREAD

**Issue by mkalioby** [Yubico/python-fido2#31]
How can we serialize the auth_data.credential_data to store as JSON in the user's profile?

Answer as Py2 and Py3 will be appreciated

**Comment by dainnilsson** [comment]
The AttestedCredentialData object uses a binary format, and as such cannot be directly serialized to JSON. I would suggest base64 encoding the object and storing it as a string:

```
from fido2.utils import websafe_encode, websafe_decode
from fido2.ctap2 import AttestedCredentialData

encoded = websafe_encode(auth_data.credential_data)  # Store this value

credential_data = AttestedCredentialData(websafe_decode(encoded))  # Restored from serialized value
```
