### ISSUE TITLE
Get Authencator ID 

### ISSUE THREAD

**Issue by mkalioby** [Yubico/python-fido2#32]
Which attribute holds an authenticator unique identifier to make sure that the authenticator is NOT used by another user?

In U2F, we used to check the X509 certificate.

Thanks in advance

**Comment by dainnilsson** [comment]
I'm not sure what you mean. The x509 certificate in U2F is NOT unique per authenticator.

**Comment by mkalioby** [comment]
I need to find a way in webauthn to make sure that the authenticator isn't registered before

**Comment by dainnilsson** [comment]
That isn't possible, by design, for both for Webauthn and U2F.

**Comment by mkalioby** [comment]
OK, another question, can we know the type of the authenticator?
