### ISSUE TITLE
Regarding Yubico Email

### ISSUE THREAD

**Issue by mkalioby** [Yubico/python-fido2#38]
Regarding Yubico email that was sent yesterday to developers 'Developers implementing FIDO U2F, update to Chrome coming in v 72', Is the library affected by this and needs a fix, or it is safe with Chrome v72+?

Thanks

**Comment by elukewalker** [comment]
The python-fido2 library follows the spec and uses web safe encoding. See [the websafe_encode() utility function](https://github.com/Yubico/python-fido2/blob/1edb0d9d4e73bf4d28ded531a7131a1fd8db2bd4/fido2/utils.py#L114). Chrome users will be impacted.

**Comment by mkalioby** [comment]
Thanks
