### ISSUE TITLE
Inconsistent Attestation Object keys

### ISSUE THREAD

**Issue by rianhunter** [Yubico/python-fido2#44]
The CBOR value for the FMT key is 0x1 in ctap2.py:

https://github.com/Yubico/python-fido2/blob/28602647cdd8003fcbd08b34898f93769f32c856/fido2/ctap2.py#L337

But in the official spec, the value is 0x2:

https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#authenticatorMakeCredential

Is this a bug?

**Comment by dainnilsson** [comment]
I believe this to be an error in the spec. If you scroll down to `Example 4` below in the section you linked, you can see in the part labeled `authenticatorMakeCredential_Response response:` that the format is actually using the key `1` there. Also, section 6.2 (https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#responses) shows `fmt` as using the key 1.

**Comment by rianhunter** [comment]
Yes, I've seen that browsers implement it the way you do. There is also another error in the spec from what I can tell. Can you report that to the spec maintainers?

**Comment by dainnilsson** [comment]
I've checked, and this issue has already been fixed in the working draft of the document, so the next publication should have the correct values.
