### ISSUE TITLE
Add annotations

### ISSUE THREAD

**Issue by ziima** [Yubico/python-fido2#45]
Annotations would help a lot. Any chance they we can see them soon?

**Comment by ziima** [comment]
It would most likely require to drop Python 2.7, but its only supported until the end of this year anyway.

**Comment by dainnilsson** [comment]
We have some typing information in the docstrings, but far from everywhere. Once Python 2 is EOL we'll most likely look at dropping support for it, which would allow us to take advantage of python3-only features.

**Comment by JohnVillalovos** [comment]
> We have some typing information in the docstrings, but far from everywhere. Once Python 2 is EOL we'll most likely look at dropping support for it, which would allow us to take advantage of python3-only features.

Python 2 is now EOL. Does this project care anymore about supporting Python 2? I'm hoping the answer is no 😊

**Comment by dainnilsson** [comment]
python-fido2 1.0.0rc1 is now released (with final coming in about a month). Support for Python < 3.7 has been dropped, and many annotations as well as type checking through mypy has been added.

**Comment by ziima** [comment]
Nice :+1:
