### ISSUE TITLE
Fix cbor encoding cycle

### ISSUE THREAD

**Issue by ziima** [Yubico/python-fido2#46]
Cycle through cbor encoding doesn't return the original value. I'd expect
```python
from fido2 import cbor
a = 42
a == cbor.loads(cbor.dumps(a))
```
to be true, but it isn't, because `loads` returns a tuple of two. I'd suggest to modify `loads` to return only decoded value and provide other function for cases where needed (`ctap2` module).

**Comment by dainnilsson** [comment]
The cbor module isn't really meant to be used outside of the context of this project, and the current behavior is more useful for that. Maybe the naming could have been better, but I don't think changing that now (breaking backwards compatibility) is worth doing.

**Comment by ziima** [comment]
I disagree, because it's not entirely internal function. It is used for encoding and decoding requests in server example. There it becomes part of the public API and as such I would expect it to behave appropriately.

Or it should be kept only as an internal function and removed from examples to avoid confusion.

**Comment by dainnilsson** [comment]
Having thought about it some more I've reconsidered. The current names are bad for other reasons as well (the `s` in loads/dumps from the `json` module most likely stand for `string` and here we're dealing with bytes). I'll change the function named, and probably add a function which decodes cbor bytes and only has a single return value in addition to the existing ones.

**Comment by ziima** [comment]
Looks good. Thanks.
