### ISSUE TITLE
NFC Fido2

### ISSUE THREAD

**Issue by merlokk** [Yubico/python-fido2#47]
Do you have interest to make this library compatible with NFC u2f/fido2 channel via pyscard ?

**Comment by dainnilsson** [comment]
Assuming it can be done without requiring vast changes to the existing code, and that it is done in a way where pyscard is an optional dependency, then yes, we'd be open to adding NFC support.

**Comment by merlokk** [comment]
there will be small changes. ok. ill try)

**Comment by merlokk** [comment]
starting... https://github.com/merlokk/python-fido2/tree/pcsc

**Comment by merlokk** [comment]
#51
