### ISSUE TITLE
Windows 10 1903 does not work 

### ISSUE THREAD

**Issue by dmazzella** [Yubico/python-fido2#55]
After update to Windows 10 1903 yubikey devices are no longer listed and consequently python-fido2 cannot be used

**Comment by mkalioby** [comment]
Strange, it is working with me fine with fido2==0.6
as shown in the attached image
<img width="342" alt="CredentialUIBroker_dOoCBl8NbC" src="https://user-images.githubusercontent.com/10414020/59424143-bffaa080-8dd3-11e9-8abf-78de0adacb69.png">

**Comment by dainnilsson** [comment]
Windows 10 1903 introduces its own WebAuthn API to interface with FIDO authenticators and blocks access from others when not running as administrator. The recommended solution is to use the Windows APIs (https://github.com/microsoft/webauthn). A workaround is to run as Administrator.

**Comment by dmazzella** [comment]
Thanks, i have tried as administrator and work correctly.
