### ISSUE TITLE
Incorrect CTAPHID_CANCEL response processing

### ISSUE THREAD

**Issue by andrewkozlik** [Yubico/python-fido2#69]
According to https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#usb-hid-cancel:

> The CTAPHID_CANCEL command MAY be sent by the client during ongoing processing of a CTAPHID_CBOR request. The CTAP2_ERR_KEEPALIVE_CANCEL response MUST be the response to that request, not an error response in the HID transport.

Thus if the client sends a CTAPHID_CANCEL command to cancel an outstanding CTAPHID_CBOR request, then the authenticator must respond with "9000012d". However, when this happens, CtapHidDevice::Call() incorrectly interprets this response as an invalid command, raising CtapError(CtapError.ERR.INVALID_COMMAND) instead of CtapError(CtapError.ERR.KEEPALIVE_CANCEL).

https://github.com/Yubico/python-fido2/blob/cacc0c4fdcd9fd0503edca06e7b03ca0964d56ec/fido2/hid.py#L106

**Comment by dainnilsson** [comment]
I'm not seeing this described behavior myself. How are you attempting to send the CANCEL command? The intended mechanism for cancelling a request is via the event parameter passed to make_credential/get_assertion (or the timeout parameter to the Fido2Client methods).

**Comment by andrewkozlik** [comment]
I think I encountered the bug when I set the timeout parameter in Fido2Client::get_assertion(). The get_assertion() method works correctly and ensures that CTAPHID_CANCEL is sent after the given timeout. The point of the issue is that when the autheticator correctly responds to the cancel command with "\x90\x00\x01\x2d", then the CtapHidDevice::Call() incorrectly interprets this response.

**Comment by andrewkozlik** [comment]
The `9000012d` response I am giving is without the Channel ID. So `90` indicates that it's a response to the MakeCredential request (as requred by the CTAP2 spec quoted above), `0001` is the data length and `2d` is the error code CTAP2_ERR_KEEPALIVE_CANCEL. The authenticator you are using is clearly giving an incorrect response to the CTAPHID_CANCEL command, because responding with `bf` (CTAPHID_ERROR) is explicitly forbidden by the spec, see the quote in my initial comment. So the reason you are not observing the behavior is because the bug in your authenticator effectively cancels out with the bug in the python-fido2 library.

**Comment by dainnilsson** [comment]
Yeah, I see what you're saying. Let me investigate a bit and get back to you.

**Comment by dainnilsson** [comment]
Incorrect behavior verified and fixed, thanks for reporting!
