### ISSUE TITLE
Security Keys (USB, NFC, Bluetooth) working on iOS

### ISSUE THREAD

**Issue by mkalioby** [Yubico/python-fido2#84]
Dear All,

With iOS 13.3, users can use Security Keys (USB, NFC, Bluetooth) on Safari, and i tested it using Yubico 5Ci and it worked like charm using this library

**Comment by cloud-hybrid** [comment]
Confirmed, too. Works great.

**Comment by dainnilsson** [comment]
Happy to hear things are working for you!
