### ISSUE TITLE
openbsd switched to fido(4)

### ISSUE THREAD

**Issue by reyk** [Yubico/python-fido2#85]
FYI, OpenBSD switched FIDO devices to a new dedicated driver, see http://man.openbsd.org/fido.4

The reason is that we want to restrict access to uhid devices and to stop relying on ioctls (for sandboxes/pledge(2)) just to open a read/write device. See the related libfido2 changes:

https://github.com/openbsd/src/commit/1ba9f8e24a930839b47e1417a70ad7b6ffac57d7#diff-dac461f456607e2f51eb0af6200db2fb

**Comment by dainnilsson** [comment]
Thanks for the heads up. The changes don't look too complicated, but having never used OpenBSD myself I'd prefer if someone who can at least test things out and make sure it works do the work. Also, I assume we'd have to do some check to see if the "old method" or the "new method" should be used?

**Comment by worr** [comment]
I wrote the original OpenBSD patch, so I'm happy to take this one.
