### ISSUE TITLE
Installation on Ubuntu tries to install uhid-freebsd

### ISSUE THREAD

**Issue by mkeefe-ac** [Yubico/python-fido2#88]
I encountered this issue while trying to install gimme-aws-creds on Xubuntu 16.04.  It pulls in fido2 which triggered the attempted installation of uhid-freebsd.  

Installing the prior version of fido2 avoids the issue and unblocked me.  However, it is unclear why this FreeBSD package was getting pulled into a LInux installation.

**Comment by mkalioby** [comment]
Update pip to the latest and it will work smoothly
